---
# tasks file for deploy

- name: Criando o blue green deploy
  hosts: docker
  tasks:
    - name: Validando o virtualhost ativo no nginx
      command: "test -f /etc/nginx/sites-enabled/green.conf"
      register: vhost
      ignore_errors: yes

    - name: Copiando a index do green
      copy:
        src: /var/lib/jenkins/workspace/deploy_green_blue/index.html
        dest: /green/index.html
      when: vhost.rc == 1

    - name: Copiando a index do blue
      copy:
        src: /var/lib/jenkins/workspace/deploy_green_blue/index.html
        dest: /blue/index.html
      when: vhost.rc == 0

    - name: Pegando o IP do green
      shell: "docker exec green hostname -I"
      register: ipgreen
      when: vhost.rc == 1

    - name: Pegando o IP do blue
      shell: "docker exec blue hostname -I"
      register: ipblue
      when: vhost.rc == 0

    - name: Criando o vhost do blue
      template:
        src: ../files/vhost_blue.conf
        dest: /etc/nginx/sites-enabled/blue.conf
      when: vhost.rc == 0

    - name: Apagando o vhost green
      file:
        path: /etc/nginx/sites-enabled/green.conf
        state: absent

    - name: Criando o vhost do green
      template:
        src: ../files/vhost_green.conf
        dest: /etc/nginx/sites-enabled/green.conf
      when: vhost.rc == 1

    - name: Apagando o vhost blue
      file:
        path: /etc/nginx/sites-enabled/blue.conf
        state: absent
      when: vhost.rc == 1

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
